# Run inside the certificates folder. Renames certificate files to safe names (Netlify rejects # & + ( ) in names).
$ErrorActionPreference='Continue'
if(Test-Path -LiteralPath 'Farhan HP Life Professional Networking for Career Growth Certificate.jpg'){Rename-Item -LiteralPath 'Farhan HP Life Professional Networking for Career Growth Certificate.jpg' -NewName 'hp-life-professional-networking-for-career-growth-certificate.jpg'}else{Write-Host 'MISSING: Farhan HP Life Professional Networking for Career Growth Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Harwest International Business College HRM Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Harwest International Business College HRM Certificate.jpg' -NewName 'harwest-international-business-college-hrm-certificate.jpg'}else{Write-Host 'MISSING: Farhan Harwest International Business College HRM Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Linkedln Learning Microsoft Security Essentials Concepts Solutions and AIPowered Protection Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Linkedln Learning Microsoft Security Essentials Concepts Solutions and AIPowered Protection Certificate.jpg' -NewName 'linkedln-learning-microsoft-security-essentials-concepts-solutions-and-aipowered-protection-certificate.jpg'}else{Write-Host 'MISSING: Farhan Linkedln Learning Microsoft Security Essentials Concepts Solutions and AIPowered Protection Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Researcher Academy Gen AI Use Research Workflow Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Researcher Academy Gen AI Use Research Workflow Certificate.jpg' -NewName 'researcher-academy-gen-ai-use-research-workflow-certificate.jpg'}else{Write-Host 'MISSING: Farhan Researcher Academy Gen AI Use Research Workflow Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Researcher Academy Enhance Chance Serendipitous Research Discovery Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Researcher Academy Enhance Chance Serendipitous Research Discovery Certificate.jpg' -NewName 'researcher-academy-enhance-chance-serendipitous-research-discovery-certificate.jpg'}else{Write-Host 'MISSING: Farhan Researcher Academy Enhance Chance Serendipitous Research Discovery Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Researcher Academy Research Design Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Researcher Academy Research Design Certificate.jpg' -NewName 'researcher-academy-research-design-certificate.jpg'}else{Write-Host 'MISSING: Farhan Researcher Academy Research Design Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Researcher Academy Intersectional Analysis Into Research Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Researcher Academy Intersectional Analysis Into Research Certificate.jpg' -NewName 'researcher-academy-intersectional-analysis-into-research-certificate.jpg'}else{Write-Host 'MISSING: Farhan Researcher Academy Intersectional Analysis Into Research Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Researcher Academy Generative and Agentic AI Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Researcher Academy Generative and Agentic AI Certificate.jpg' -NewName 'researcher-academy-generative-and-agentic-ai-certificate.jpg'}else{Write-Host 'MISSING: Farhan Researcher Academy Generative and Agentic AI Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Researcher Academy Ethical AI in Research Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Researcher Academy Ethical AI in Research Certificate.jpg' -NewName 'researcher-academy-ethical-ai-in-research-certificate.jpg'}else{Write-Host 'MISSING: Farhan Researcher Academy Ethical AI in Research Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan HackerRank SQL (Advanced) Certificate.jpg'){Rename-Item -LiteralPath 'Farhan HackerRank SQL (Advanced) Certificate.jpg' -NewName 'hackerrank-sql-advanced-certificate.jpg'}else{Write-Host 'MISSING: Farhan HackerRank SQL (Advanced) Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan HackerRank Java (Basic) Certificate.jpg'){Rename-Item -LiteralPath 'Farhan HackerRank Java (Basic) Certificate.jpg' -NewName 'hackerrank-java-basic-certificate.jpg'}else{Write-Host 'MISSING: Farhan HackerRank Java (Basic) Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan HackerRank SQL (Intermediate) Certificate.jpg'){Rename-Item -LiteralPath 'Farhan HackerRank SQL (Intermediate) Certificate.jpg' -NewName 'hackerrank-sql-intermediate-certificate.jpg'}else{Write-Host 'MISSING: Farhan HackerRank SQL (Intermediate) Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan HackerRank CSS (Basic) Certificate.jpg'){Rename-Item -LiteralPath 'Farhan HackerRank CSS (Basic) Certificate.jpg' -NewName 'hackerrank-css-basic-certificate.jpg'}else{Write-Host 'MISSING: Farhan HackerRank CSS (Basic) Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan HackerRank SQL (Basic) Certificate.jpg'){Rename-Item -LiteralPath 'Farhan HackerRank SQL (Basic) Certificate.jpg' -NewName 'hackerrank-sql-basic-certificate.jpg'}else{Write-Host 'MISSING: Farhan HackerRank SQL (Basic) Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basic of UI Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basic of UI Certificate.jpg' -NewName 'uniathena-basic-of-ui-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basic of UI Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic Claude With a Anthropic API Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic Claude With a Anthropic API Certificate.jpg' -NewName 'anthropic-claude-with-a-anthropic-api-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic Claude With a Anthropic API Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic AI Fluency - Framwork&Foundation Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic AI Fluency - Framwork&Foundation Certificate.jpg' -NewName 'anthropic-ai-fluency-framwork-and-foundation-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic AI Fluency - Framwork&Foundation Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic Claude Code in Action Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic Claude Code in Action Certificate.jpg' -NewName 'anthropic-claude-code-in-action-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic Claude Code in Action Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic Introduction to Claude Cowork Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic Introduction to Claude Cowork Certificate.jpg' -NewName 'anthropic-introduction-to-claude-cowork-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic Introduction to Claude Cowork Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic Claude Platform 101 Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic Claude Platform 101 Certificate.jpg' -NewName 'anthropic-claude-platform-101-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic Claude Platform 101 Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic Claude Code 101 Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic Claude Code 101 Certificate.jpg' -NewName 'anthropic-claude-code-101-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic Claude Code 101 Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Anthropic Claude 101 Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Anthropic Claude 101 Certificate.jpg' -NewName 'anthropic-claude-101-certificate.jpg'}else{Write-Host 'MISSING: Farhan Anthropic Claude 101 Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Microsoft Azure Essentials by Microsoft Press Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Microsoft Azure Essentials by Microsoft Press Certificate.jpg' -NewName 'microsoft-azure-essentials-by-microsoft-press-certificate.jpg'}else{Write-Host 'MISSING: Farhan Microsoft Azure Essentials by Microsoft Press Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basics of UI UX Strategy Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basics of UI UX Strategy Certificate.jpg' -NewName 'uniathena-basics-of-ui-ux-strategy-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basics of UI UX Strategy Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basic in AI Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basic in AI Certificate.jpg' -NewName 'uniathena-basic-in-ai-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basic in AI Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Microsoft Azure Essentials Professional Linkdin Microsoft  Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Microsoft Azure Essentials Professional Linkdin Microsoft  Certificate.jpg' -NewName 'microsoft-azure-essentials-professional-linkdin-microsoft-certificate.jpg'}else{Write-Host 'MISSING: Farhan Microsoft Azure Essentials Professional Linkdin Microsoft  Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basics of Motivation and Leadership Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basics of Motivation and Leadership Certificate.jpg' -NewName 'uniathena-basics-of-motivation-and-leadership-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basics of Motivation and Leadership Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basic in HRM Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basic in HRM Certificate.jpg' -NewName 'uniathena-basic-in-hrm-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basic in HRM Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Gemini Educator Certificate.png'){Rename-Item -LiteralPath 'Farhan Gemini Educator Certificate.png' -NewName 'gemini-educator-certificate.png'}else{Write-Host 'MISSING: Farhan Gemini Educator Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Gemini Student Certificate.png'){Rename-Item -LiteralPath 'Farhan Gemini Student Certificate.png' -NewName 'gemini-student-certificate.png'}else{Write-Host 'MISSING: Farhan Gemini Student Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cisco Packet Tracer Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cisco Packet Tracer Certificate.jpg' -NewName 'cisco-packet-tracer-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cisco Packet Tracer Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cisco JavaScript Essentials 1 Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cisco JavaScript Essentials 1 Certificate.jpg' -NewName 'cisco-javascript-essentials-1-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cisco JavaScript Essentials 1 Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Udemy Microsoft Azure Administrator Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Udemy Microsoft Azure Administrator Certificate.jpg' -NewName 'udemy-microsoft-azure-administrator-certificate.jpg'}else{Write-Host 'MISSING: Farhan Udemy Microsoft Azure Administrator Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Coursera Build a computer vision app with Azure Cognitive Services Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Coursera Build a computer vision app with Azure Cognitive Services Certificate.jpg' -NewName 'coursera-build-a-computer-vision-app-with-azure-cognitive-services-certificate.jpg'}else{Write-Host 'MISSING: Farhan Coursera Build a computer vision app with Azure Cognitive Services Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Coursera Graphic Design Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Coursera Graphic Design Certificate.jpg' -NewName 'coursera-graphic-design-certificate.jpg'}else{Write-Host 'MISSING: Farhan Coursera Graphic Design Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan ScholarHat MongoDB Foundations Certificate.jpg'){Rename-Item -LiteralPath 'Farhan ScholarHat MongoDB Foundations Certificate.jpg' -NewName 'scholarhat-mongodb-foundations-certificate.jpg'}else{Write-Host 'MISSING: Farhan ScholarHat MongoDB Foundations Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan ScholarHat JavaScript Programming Certificate.jpg'){Rename-Item -LiteralPath 'Farhan ScholarHat JavaScript Programming Certificate.jpg' -NewName 'scholarhat-javascript-programming-certificate.jpg'}else{Write-Host 'MISSING: Farhan ScholarHat JavaScript Programming Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan ScholarHat C# Programming Certificate.jpg'){Rename-Item -LiteralPath 'Farhan ScholarHat C# Programming Certificate.jpg' -NewName 'scholarhat-csharp-programming-certificate.jpg'}else{Write-Host 'MISSING: Farhan ScholarHat C# Programming Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan ScholarHat Java Programming Certificate.jpg'){Rename-Item -LiteralPath 'Farhan ScholarHat Java Programming Certificate.jpg' -NewName 'scholarhat-java-programming-certificate.jpg'}else{Write-Host 'MISSING: Farhan ScholarHat Java Programming Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan ScholarHat AWS Cloud Practitioner Foundation Certificate.jpg'){Rename-Item -LiteralPath 'Farhan ScholarHat AWS Cloud Practitioner Foundation Certificate.jpg' -NewName 'scholarhat-aws-cloud-practitioner-foundation-certificate.jpg'}else{Write-Host 'MISSING: Farhan ScholarHat AWS Cloud Practitioner Foundation Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Microsoft 365 Endpoint Administrator Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Microsoft 365 Endpoint Administrator Certificate.jpg' -NewName 'microsoft-365-endpoint-administrator-certificate.jpg'}else{Write-Host 'MISSING: Farhan Microsoft 365 Endpoint Administrator Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basics of Microsoft Power BI Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basics of Microsoft Power BI Certificate.jpg' -NewName 'uniathena-basics-of-microsoft-power-bi-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basics of Microsoft Power BI Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena MS Excel Formulas and Functions Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena MS Excel Formulas and Functions Certificate.jpg' -NewName 'uniathena-ms-excel-formulas-and-functions-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena MS Excel Formulas and Functions Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Fundamentals of English Grammar Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Fundamentals of English Grammar Certificate.jpg' -NewName 'uniathena-fundamentals-of-english-grammar-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Fundamentals of English Grammar Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cognitive Class ai Deep Learning Fundamentals Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cognitive Class ai Deep Learning Fundamentals Certificate.jpg' -NewName 'cognitive-class-ai-deep-learning-fundamentals-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cognitive Class ai Deep Learning Fundamentals Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cognitive Class ai SQL and Relational Databases Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cognitive Class ai SQL and Relational Databases Certificate.jpg' -NewName 'cognitive-class-ai-sql-and-relational-databases-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cognitive Class ai SQL and Relational Databases Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan SkillSoft Percipio Search Problems.jpg'){Rename-Item -LiteralPath 'Farhan SkillSoft Percipio Search Problems.jpg' -NewName 'skillsoft-percipio-search-problems.jpg'}else{Write-Host 'MISSING: Farhan SkillSoft Percipio Search Problems.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cursa MongoDB Database Certificate.jpeg'){Rename-Item -LiteralPath 'Farhan Cursa MongoDB Database Certificate.jpeg' -NewName 'cursa-mongodb-database-certificate.jpeg'}else{Write-Host 'MISSING: Farhan Cursa MongoDB Database Certificate.jpeg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Master ChatGPT Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Master ChatGPT Certificate.jpg' -NewName 'uniathena-master-chatgpt-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Master ChatGPT Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basic of Python Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basic of Python Certificate.jpg' -NewName 'uniathena-basic-of-python-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basic of Python Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Essentials of Data Visualization using MS Excel.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Essentials of Data Visualization using MS Excel.jpg' -NewName 'uniathena-essentials-of-data-visualization-using-ms-excel.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Essentials of Data Visualization using MS Excel.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basic in Machine Learning Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basic in Machine Learning Certificate.jpg' -NewName 'uniathena-basic-in-machine-learning-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basic in Machine Learning Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cisco Network Basic Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cisco Network Basic Certificate.jpg' -NewName 'cisco-network-basic-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cisco Network Basic Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Simple Learn Skill Microsoft Excel Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Simple Learn Skill Microsoft Excel Certificate.jpg' -NewName 'simple-learn-skill-microsoft-excel-certificate.jpg'}else{Write-Host 'MISSING: Farhan Simple Learn Skill Microsoft Excel Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cisco Cyber Security Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cisco Cyber Security Certificate.jpg' -NewName 'cisco-cyber-security-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cisco Cyber Security Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Simple Learn Skill Azure Fundamantal Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Simple Learn Skill Azure Fundamantal Certificate.jpg' -NewName 'simple-learn-skill-azure-fundamantal-certificate.jpg'}else{Write-Host 'MISSING: Farhan Simple Learn Skill Azure Fundamantal Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena SQL Mastery With MySQL Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena SQL Mastery With MySQL Certificate.jpg' -NewName 'uniathena-sql-mastery-with-mysql-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena SQL Mastery With MySQL Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Coursera PowerPoint Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Coursera PowerPoint Certificate.jpg' -NewName 'coursera-powerpoint-certificate.jpg'}else{Write-Host 'MISSING: Farhan Coursera PowerPoint Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan LearnzConnect Git Github Foundation Certificate.png'){Rename-Item -LiteralPath 'Farhan LearnzConnect Git Github Foundation Certificate.png' -NewName 'learnzconnect-git-github-foundation-certificate.png'}else{Write-Host 'MISSING: Farhan LearnzConnect Git Github Foundation Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Simple Learn Skill AI Beginner Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Simple Learn Skill AI Beginner Certificate.jpg' -NewName 'simple-learn-skill-ai-beginner-certificate.jpg'}else{Write-Host 'MISSING: Farhan Simple Learn Skill AI Beginner Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan LearnzConnect SQL Mastery With MySQL Certificate.png'){Rename-Item -LiteralPath 'Farhan LearnzConnect SQL Mastery With MySQL Certificate.png' -NewName 'learnzconnect-sql-mastery-with-mysql-certificate.png'}else{Write-Host 'MISSING: Farhan LearnzConnect SQL Mastery With MySQL Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Simple Learn Skill Cyber Security Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Simple Learn Skill Cyber Security Certificate.jpg' -NewName 'simple-learn-skill-cyber-security-certificate.jpg'}else{Write-Host 'MISSING: Farhan Simple Learn Skill Cyber Security Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Simple Learn Skill Ethical Hacking Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Simple Learn Skill Ethical Hacking Certificate.jpg' -NewName 'simple-learn-skill-ethical-hacking-certificate.jpg'}else{Write-Host 'MISSING: Farhan Simple Learn Skill Ethical Hacking Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Simple Learn Skill Java Program Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Simple Learn Skill Java Program Certificate.jpg' -NewName 'simple-learn-skill-java-program-certificate.jpg'}else{Write-Host 'MISSING: Farhan Simple Learn Skill Java Program Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Ai Foundations For Educators IBM Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Ai Foundations For Educators IBM Certificate.jpg' -NewName 'ai-foundations-for-educators-ibm-certificate.jpg'}else{Write-Host 'MISSING: Farhan Ai Foundations For Educators IBM Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cisco C++ Essentials 1 Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cisco C++ Essentials 1 Certificate.jpg' -NewName 'cisco-cplusplus-essentials-1-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cisco C++ Essentials 1 Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Cisco Ethical Hacker Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Cisco Ethical Hacker Certificate.jpg' -NewName 'cisco-ethical-hacker-certificate.jpg'}else{Write-Host 'MISSING: Farhan Cisco Ethical Hacker Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Google Ads Ai Powered Performance Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Google Ads Ai Powered Performance Certificate.jpg' -NewName 'google-ads-ai-powered-performance-certificate.jpg'}else{Write-Host 'MISSING: Farhan Google Ads Ai Powered Performance Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Google Ads Apps Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Google Ads Apps Certificate.jpg' -NewName 'google-ads-apps-certificate.jpg'}else{Write-Host 'MISSING: Farhan Google Ads Apps Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Google Ads Search Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Google Ads Search Certificate.jpg' -NewName 'google-ads-search-certificate.jpg'}else{Write-Host 'MISSING: Farhan Google Ads Search Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Wireframing and Prototyping IBM Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Wireframing and Prototyping IBM Certificate.jpg' -NewName 'wireframing-and-prototyping-ibm-certificate.jpg'}else{Write-Host 'MISSING: Farhan Wireframing and Prototyping IBM Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Uniathena Basic Python Programming Certificate.jpg'){Rename-Item -LiteralPath 'Farhan Uniathena Basic Python Programming Certificate.jpg' -NewName 'uniathena-basic-python-programming-certificate.jpg'}else{Write-Host 'MISSING: Farhan Uniathena Basic Python Programming Certificate.jpg' -ForegroundColor Red}
if(Test-Path -LiteralPath 'FarhanSpeed Memory IQ Certificate.png'){Rename-Item -LiteralPath 'FarhanSpeed Memory IQ Certificate.png' -NewName 'speed-memory-iq-certificate.png'}else{Write-Host 'MISSING: FarhanSpeed Memory IQ Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Diploma in English Certificate.png'){Rename-Item -LiteralPath 'Farhan Diploma in English Certificate.png' -NewName 'diploma-in-english-certificate.png'}else{Write-Host 'MISSING: Farhan Diploma in English Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan Diploma in ICT Certificate.png'){Rename-Item -LiteralPath 'Farhan Diploma in ICT Certificate.png' -NewName 'diploma-in-ict-certificate.png'}else{Write-Host 'MISSING: Farhan Diploma in ICT Certificate.png' -ForegroundColor Red}
if(Test-Path -LiteralPath 'Farhan SAC Digital Marketing Certificate.jpg'){Rename-Item -LiteralPath 'Farhan SAC Digital Marketing Certificate.jpg' -NewName 'sac-digital-marketing-certificate.jpg'}else{Write-Host 'MISSING: Farhan SAC Digital Marketing Certificate.jpg' -ForegroundColor Red}
Write-Host 'Done.' -ForegroundColor Green
